spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
        show-sql: true
        format_sql: true
        hbm2ddl.auto: validate

server:
  port: 8090

